//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 11:14:05 PM IST 
//


package com.salesforce.th.invoice_web_service;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.salesforce.th.invoice_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.salesforce.th.invoice_web_service
     * 
     */
    public ObjectFactory() {
    }


    /**
     * Create an instance of {@link BillProjectResponse }
     * 
     */
    public BillProjectResponse createBillProjectResponse() {
        return new BillProjectResponse();
    }


    /**
     * Create an instance of {@link BillProjectRequest }
     * 
     */
    public BillProjectRequest createBillProjectRequest() {
        return new BillProjectRequest();
    }

    /**
     * Create an instance of {@link Project }
     * 
     */
    public Project createProject() {
        return new Project();
    }

}
